apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-ws
  name: {{ .Values.name }}-ws
  namespace: {{ .Release.Namespace }}
{{- with .Values.wsConfigmap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}