apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-operator
  name: {{ .Values.name }}-operator
  namespace: {{ .Release.Namespace }}
{{- with .Values.operConfigmap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}