apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-role
  name: {{ .Values.name }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - "batch"
  resources:
  - pods
  - pods/log
  - events
  - configmaps
  - secrets
  - jobs
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-rb
  name: {{ .Values.name }}-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-sa
  namespace: {{ .Release.Namespace }} 
