apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-operator
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: api
  - port: 80
    protocol: TCP
    targetPort: 80
    name: web
  selector:
    app.kubernetes.io/name: {{ .Values.name }}-operator